version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./sql-data:/var/opt/mssql
    ports:
      - "11433:1433"
    restart: unless-stopped
