version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./app:/app
  php:
    # image: php:7.4-fpm
    build:
      context: ./php
    volumes:
      - ./app:/app
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"

  maria:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "P@ssw0rd"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
