name: Publish Docker image
on:
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          context: ./server-info
          file: ./server-info/Dockerfile
          username: ${{ gihub.actor }}
          password: ${{ secrets.CR_PAT }}
          repository: shockzinfinity/server-info
          tag: latest
